pipeline {
  agent {
    docker {
      image 'hashicorp/terraform:light'
      args '--entrypoint='
    }
  }
  stages {
        stage('Change Directory') {
            sh 'cd terraform/'
        }
        stage('Terraform Init') {
            steps {
                sh 'terraform init -no-color'
            }
        }
        // Optional wait for approval
        //input 'Approve Plan?'

        stage ('Terraform Validate') {
            sh "terraform validate -no-color"
        }
  }
}
