pipeline {
    agent any
    tools {
        terraform 'terraform'
    }
    stages {
        stage('Change Dir') {
           steps{
               sh 'cd terraform/'
           }
        }
        stage('Terraform Init') {
           steps{
                sh 'terraform init'
           }
        }
        stage('Terraform Validate') {
            steps{
                sh 'terraform validate'
            }

        }
    }
}
