pipeline {
    agent any
    tools {
        terraform 'terraform-1.2.2'
    }
    stages {
        stage('Terraform Init') {
           steps{
                sh 'cd ../terraform && terraform init'
           }
        }
        stage('Terraform Validate') {
            steps{
                sh 'cd ../terraform && terraform validate'
            }

        }
    }
}
